//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.04 at 08:02:09 AM BST
//

package uk.gov.ons.census.actionsvc.model.dto.instruction;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for ActionUpdate complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ActionUpdate"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ons.gov.uk/ctp/response/action/message/instruction}Action"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="priority" type="{http://ons.gov.uk/ctp/response/action/message/instruction}Priority"/&gt;
 *         &lt;element name="events" type="{http://ons.gov.uk/ctp/response/action/message/instruction}ActionEvent"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ActionUpdate",
    propOrder = {"priority", "events"})
public class ActionUpdate extends Action implements Serializable {

  private static final long serialVersionUID = 8297030705722814170L;

  @XmlElement(required = true)
  @XmlSchemaType(name = "string")
  protected Priority priority;

  @XmlElement(required = true)
  protected ActionEvent events;

  /** Default no-arg constructor */
  public ActionUpdate() {
    super();
  }

  /** Fully-initialising value constructor */
  public ActionUpdate(
      final String actionId,
      final boolean responseRequired,
      final Priority priority,
      final ActionEvent events) {
    super(actionId, responseRequired);
    this.priority = priority;
    this.events = events;
  }

  /**
   * Gets the value of the priority property.
   *
   * @return possible object is {@link Priority }
   */
  public Priority getPriority() {
    return priority;
  }

  /**
   * Sets the value of the priority property.
   *
   * @param value allowed object is {@link Priority }
   */
  public void setPriority(Priority value) {
    this.priority = value;
  }

  /**
   * Gets the value of the events property.
   *
   * @return possible object is {@link ActionEvent }
   */
  public ActionEvent getEvents() {
    return events;
  }

  /**
   * Sets the value of the events property.
   *
   * @param value allowed object is {@link ActionEvent }
   */
  public void setEvents(ActionEvent value) {
    this.events = value;
  }
}
