//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.04 at 08:02:09 AM BST
//

package uk.gov.ons.census.actionsvc.model.dto.instruction;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for ActionInstruction complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ActionInstruction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice&gt;
 *         &lt;element name="actionRequest" type="{http://ons.gov.uk/ctp/response/action/message/instruction}ActionRequest"/&gt;
 *         &lt;element name="actionUpdate" type="{http://ons.gov.uk/ctp/response/action/message/instruction}ActionUpdate"/&gt;
 *         &lt;element name="actionCancel" type="{http://ons.gov.uk/ctp/response/action/message/instruction}ActionCancel"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ActionInstruction",
    propOrder = {"actionCancel", "actionUpdate", "actionRequest"})
@XmlRootElement(name = "actionInstruction")
public class ActionInstruction implements Serializable {

  private static final long serialVersionUID = 8297030705722814170L;
  protected ActionCancel actionCancel;
  protected ActionUpdate actionUpdate;
  protected ActionRequest actionRequest;

  /** Default no-arg constructor */
  public ActionInstruction() {
    super();
  }

  /** Fully-initialising value constructor */
  public ActionInstruction(
      final ActionCancel actionCancel,
      final ActionUpdate actionUpdate,
      final ActionRequest actionRequest) {
    this.actionCancel = actionCancel;
    this.actionUpdate = actionUpdate;
    this.actionRequest = actionRequest;
  }

  /**
   * Gets the value of the actionCancel property.
   *
   * @return possible object is {@link ActionCancel }
   */
  public ActionCancel getActionCancel() {
    return actionCancel;
  }

  /**
   * Sets the value of the actionCancel property.
   *
   * @param value allowed object is {@link ActionCancel }
   */
  public void setActionCancel(ActionCancel value) {
    this.actionCancel = value;
  }

  /**
   * Gets the value of the actionUpdate property.
   *
   * @return possible object is {@link ActionUpdate }
   */
  public ActionUpdate getActionUpdate() {
    return actionUpdate;
  }

  /**
   * Sets the value of the actionUpdate property.
   *
   * @param value allowed object is {@link ActionUpdate }
   */
  public void setActionUpdate(ActionUpdate value) {
    this.actionUpdate = value;
  }

  /**
   * Gets the value of the actionRequest property.
   *
   * @return possible object is {@link ActionRequest }
   */
  public ActionRequest getActionRequest() {
    return actionRequest;
  }

  /**
   * Sets the value of the actionRequest property.
   *
   * @param value allowed object is {@link ActionRequest }
   */
  public void setActionRequest(ActionRequest value) {
    this.actionRequest = value;
  }
}
