//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.04 at 08:02:09 AM BST
//

package uk.gov.ons.census.actionsvc.model.dto.instruction;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for Action complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Action"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="actionId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="responseRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "Action",
    propOrder = {"actionId", "responseRequired"})
@XmlSeeAlso({ActionCancel.class, ActionUpdate.class, ActionRequest.class})
public class Action implements Serializable {

  private static final long serialVersionUID = 8297030705722814170L;

  @XmlElement(required = true)
  protected String actionId;

  protected boolean responseRequired;

  /** Default no-arg constructor */
  public Action() {
    super();
  }

  /** Fully-initialising value constructor */
  public Action(final String actionId, final boolean responseRequired) {
    this.actionId = actionId;
    this.responseRequired = responseRequired;
  }

  /**
   * Gets the value of the actionId property.
   *
   * @return possible object is {@link String }
   */
  public String getActionId() {
    return actionId;
  }

  /**
   * Sets the value of the actionId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setActionId(String value) {
    this.actionId = value;
  }

  /** Gets the value of the responseRequired property. */
  public boolean isResponseRequired() {
    return responseRequired;
  }

  /** Sets the value of the responseRequired property. */
  public void setResponseRequired(boolean value) {
    this.responseRequired = value;
  }
}
