//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.04 at 08:02:09 AM BST
//

package uk.gov.ons.census.actionsvc.model.dto.instruction;

import java.io.Serializable;
import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for ActionAddress complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ActionAddress"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="estabType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="locality" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="organisationName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="category" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="line1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="line2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="line3" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="townName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="postcode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ladCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ActionAddress",
    propOrder = {
      "type",
      "estabType",
      "locality",
      "organisationName",
      "category",
      "line1",
      "line2",
      "line3",
      "townName",
      "postcode",
      "country",
      "ladCode",
      "latitude",
      "longitude"
    })
public class ActionAddress implements Serializable {

  private static final long serialVersionUID = 8297030705722814170L;
  protected String type;
  protected String estabType;
  protected String locality;
  protected String organisationName;
  protected String category;
  protected String line1;
  protected String line2;
  protected String line3;
  protected String townName;
  protected String postcode;
  protected String country;
  protected String ladCode;
  protected BigDecimal latitude;
  protected BigDecimal longitude;

  /** Default no-arg constructor */
  public ActionAddress() {
    super();
  }

  /** Fully-initialising value constructor */
  public ActionAddress(
      final String type,
      final String estabType,
      final String locality,
      final String organisationName,
      final String category,
      final String line1,
      final String line2,
      final String line3,
      final String townName,
      final String postcode,
      final String country,
      final String ladCode,
      final BigDecimal latitude,
      final BigDecimal longitude) {
    this.type = type;
    this.estabType = estabType;
    this.locality = locality;
    this.organisationName = organisationName;
    this.category = category;
    this.line1 = line1;
    this.line2 = line2;
    this.line3 = line3;
    this.townName = townName;
    this.postcode = postcode;
    this.country = country;
    this.ladCode = ladCode;
    this.latitude = latitude;
    this.longitude = longitude;
  }

  /**
   * Gets the value of the type property.
   *
   * @return possible object is {@link String }
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   *
   * @param value allowed object is {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the estabType property.
   *
   * @return possible object is {@link String }
   */
  public String getEstabType() {
    return estabType;
  }

  /**
   * Sets the value of the estabType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setEstabType(String value) {
    this.estabType = value;
  }

  /**
   * Gets the value of the locality property.
   *
   * @return possible object is {@link String }
   */
  public String getLocality() {
    return locality;
  }

  /**
   * Sets the value of the locality property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLocality(String value) {
    this.locality = value;
  }

  /**
   * Gets the value of the organisationName property.
   *
   * @return possible object is {@link String }
   */
  public String getOrganisationName() {
    return organisationName;
  }

  /**
   * Sets the value of the organisationName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setOrganisationName(String value) {
    this.organisationName = value;
  }

  /**
   * Gets the value of the category property.
   *
   * @return possible object is {@link String }
   */
  public String getCategory() {
    return category;
  }

  /**
   * Sets the value of the category property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCategory(String value) {
    this.category = value;
  }

  /**
   * Gets the value of the line1 property.
   *
   * @return possible object is {@link String }
   */
  public String getLine1() {
    return line1;
  }

  /**
   * Sets the value of the line1 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLine1(String value) {
    this.line1 = value;
  }

  /**
   * Gets the value of the line2 property.
   *
   * @return possible object is {@link String }
   */
  public String getLine2() {
    return line2;
  }

  /**
   * Sets the value of the line2 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLine2(String value) {
    this.line2 = value;
  }

  /**
   * Gets the value of the line3 property.
   *
   * @return possible object is {@link String }
   */
  public String getLine3() {
    return line3;
  }

  /**
   * Sets the value of the line3 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLine3(String value) {
    this.line3 = value;
  }

  /**
   * Gets the value of the townName property.
   *
   * @return possible object is {@link String }
   */
  public String getTownName() {
    return townName;
  }

  /**
   * Sets the value of the townName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTownName(String value) {
    this.townName = value;
  }

  /**
   * Gets the value of the postcode property.
   *
   * @return possible object is {@link String }
   */
  public String getPostcode() {
    return postcode;
  }

  /**
   * Sets the value of the postcode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPostcode(String value) {
    this.postcode = value;
  }

  /**
   * Gets the value of the country property.
   *
   * @return possible object is {@link String }
   */
  public String getCountry() {
    return country;
  }

  /**
   * Sets the value of the country property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCountry(String value) {
    this.country = value;
  }

  /**
   * Gets the value of the ladCode property.
   *
   * @return possible object is {@link String }
   */
  public String getLadCode() {
    return ladCode;
  }

  /**
   * Sets the value of the ladCode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLadCode(String value) {
    this.ladCode = value;
  }

  /**
   * Gets the value of the latitude property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getLatitude() {
    return latitude;
  }

  /**
   * Sets the value of the latitude property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setLatitude(BigDecimal value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the longitude property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getLongitude() {
    return longitude;
  }

  /**
   * Sets the value of the longitude property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setLongitude(BigDecimal value) {
    this.longitude = value;
  }
}
