//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.04.04 at 08:02:09 AM BST
//

package uk.gov.ons.census.action.model.dto.instruction;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for ActionCancel complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ActionCancel"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://ons.gov.uk/ctp/response/action/message/instruction}Action"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="reason" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="caseId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="caseRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ActionCancel",
    propOrder = {"reason", "caseId", "caseRef"})
public class ActionCancel extends Action implements Serializable {

  private static final long serialVersionUID = 8297030705722814170L;

  @XmlElement(required = true)
  protected String reason;

  protected String caseId;
  protected String caseRef;

  /** Default no-arg constructor */
  public ActionCancel() {
    super();
  }

  /** Fully-initialising value constructor */
  public ActionCancel(
      final String actionId,
      final boolean responseRequired,
      final String reason,
      final String caseId,
      final String caseRef) {
    super(actionId, responseRequired);
    this.reason = reason;
    this.caseId = caseId;
    this.caseRef = caseRef;
  }

  /**
   * Gets the value of the reason property.
   *
   * @return possible object is {@link String }
   */
  public String getReason() {
    return reason;
  }

  /**
   * Sets the value of the reason property.
   *
   * @param value allowed object is {@link String }
   */
  public void setReason(String value) {
    this.reason = value;
  }

  /**
   * Gets the value of the caseId property.
   *
   * @return possible object is {@link String }
   */
  public String getCaseId() {
    return caseId;
  }

  /**
   * Sets the value of the caseId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCaseId(String value) {
    this.caseId = value;
  }

  /**
   * Gets the value of the caseRef property.
   *
   * @return possible object is {@link String }
   */
  public String getCaseRef() {
    return caseRef;
  }

  /**
   * Sets the value of the caseRef property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCaseRef(String value) {
    this.caseRef = value;
  }
}
