server:
  port: 8301

info:
  app:
    name: Action Processor
    version: 1.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximumPoolSize: 50

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: actionv2
        jdbc:
          lob:
            non_contextual_creation: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  inbound-queue: case.action
  action-fulfilment-inbound-queue: action.fulfilment
  events-exchange: events
  events-fulfilment-request-binding: event.fulfilment.request
  outbound-printer-queue: Action.Printer
  outbound-field-queue: Action.Field
  outbound-exchange: action-outbound-exchange
  outbound-printer-routing-key: Action.Printer.binding
  outbound-field-routing-key: Action.Field.binding
  action-case-exchange: action-case-exchange
  action-case-queue: action.events
  undelivered-mail-queue: action.undeliveredMailQueue
  consumers: 50

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/action-scheduler-healthy

scheduler:
  frequency: 1000 #milliseconds

caseapi:
  host: caseapi
  port: 8161