server:
  port: 8301

info:
  app:
    name: Action Scheduler
    version: 1.0

spring:
  task:
    scheduling:
      pool:
        size: 10

  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always
    hikari:
      maximumPoolSize: 10

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: actionv2
        jdbc:
          lob:
            non_contextual_creation: true

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/action-scheduler-healthy

scheduler:
  frequency: 1000 #milliseconds
  chunksize: 1000

fulfilment:
  batch:
    scheduled:
      time: "0 0 16 ? * *"

logging:
  level:
    org.springframework.amqp.rabbit.listener.ConditionalRejectingErrorHandler: ERROR