spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: actionsvcv2
        jdbc:
          lob:
            non_contextual_creation: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 6672
    virtualhost: /

queueconfig:
  inbound-queue: myfanout.actionqueue
  outbound-queue: exampleOutboundQueue

healthcheck:
  frequency: 1000 #milliseconds
  filename: /tmp/action-service-healthy
